### PR TITLE
Laurelin improvements (Coveralls.io + CodeClimate API)

### PR DESCRIPTION
**Pull request by oshadura**
Quick fix: Coveralls.io is actually managing not to generate "noise" in PRs, as well as CodeClimate.
(example https://github.com/JMRI/JMRI)

As soon as it will be merged, we can add 2 badges in README.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
Hi @oshadura I don't have a preference either way on what code coverage tool we use (I'll send you the token you requested in a sec), but did you notice that I got it so codecov does one of those status checks too?

Screen Shot 2019-09-25 at 10 01 52 AM

**Comment by oshadura** [comment]
> Hi @oshadura I don't have a preference either way on what code coverage tool we use (I'll send you the token you requested in a sec), but did you notice that I got it so codecov does one of those status checks too?
> 
> Screen Shot 2019-09-25 at 10 01 52 AM

Interesting! I didn't see it before in earlier PRs, but now in your latest PR (https://github.com/spark-root/laurelin/pull/61) everything looks good!
So then consider please this PR irrelevant...

**Comment by oshadura** [comment]
maybe... it is pretty :)

**Comment by PerilousApricot** [comment]
Ok! In that case, can you redo your branch to just have the CodeClimate
changes and we can work on the token stuff tomorrow via Skype?
-- 
It's dark in this basement.

**Comment by oshadura** [comment]
Closing in favor of https://github.com/spark-root/laurelin/pull/60

**Pull request closed without merging**
