### PR TITLE
Add codecov.io coverage to Travis bot

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by PerilousApricot** [comment]
Hi @oshadura -- Nice! Sorry I didn't respond to this earlier .. for some reason I didn't get a notification email from github? That's pretty annoying :(

Anyway, if I don't repsond in the future, please feel free to ping me to get my attention.

**Comment by PerilousApricot** [comment]
@oshadura I'm comfortable with either Codecov or Coveralls.io, whichever you think is the more useful interface. I was requesting that whatever service is providing the coverage measurements do it in the form of a PR status notification and not as a bot that writes comments like https://github.com/spark-root/laurelin/pull/53#issuecomment-528883480

**Comment by oshadura** [comment]
@PerilousApricot it is not possible to have it as one of Travis CI checks, because it is already part of Travis PR build. Messages are printed by Codecov.io bot, which I believe we can remove from https://codecov.io/ interface (I am not owner of repository so I don't see a lot). 

I think messages could be useful, since contributors could evaluate how much useful code they wrote :D

But actually now I am not sure, if Codecov is a right choice, because it seems like it doesn't support Java 8: https://travis-ci.org/spark-root/laurelin/builds/581709066?utm_source=github_status&utm_medium=notification

`[WARN] JavaNCSS got an error while parsing the java file /home/travis/build/spark-root/laurelin/src/main/java/edu/vanderbilt/accre/laurelin/Root.java
ParseException in STDIN
Last useful checkpoint: "edu.vanderbilt.accre.laurelin.Root.TTreeDataSourceV2PartitionReaderedu.vanderbilt.accre.laurelin.Root.TTreeDataSourceV2PartitionReader.TTreeDataSourceV2PartitionReader(CacheFactory,StructType,long,long,Map<String,SlimTBranch>,int,CollectionAccumulator<Storage>,int)"
Encountered " ">" "> "" at line 121, column 25.
Was expecting one of:
    "assert" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "enum" ...`

**Comment by PerilousApricot** [comment]
Could you add a new file called `codecov.yml` to the base of your branch with

```
coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "src/test"  # only include coverage in "tests/" folder
      app:  # declare a new status context "app"
        paths: "!src/main"  # remove all files in "tests/"
comment: off
```

I'm looking into the error you saw

**Comment by PerilousApricot** [comment]
And it looks like the cobertura-maven-plugin doesn't support Java 8, but you can replace that with another plugin via:

```
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.2</version>
				<executions>
					<execution>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
in the pom.xml

**Comment by oshadura** [comment]
@PerilousApricot hiiii! totally agree! Sorry for disappearance, I was traveling again :( ! It is on my list for today, maximum tomorrow!

**Comment by PerilousApricot** [comment]
No problem! I'm traveling too --- I added to your implementation at #56, which is currently in master. lemme know what you think!

**Pull request merged**
